### ISSUE TITLE
Is python 3.6 supported?

### ISSUE THREAD

**Issue by GolanTrevize10** [github/github-team-sync#126]
In the Readme file it says it needs Python 3.4+, but in the pipfile it says it requires 3.9

**Comment by primetheus** [comment]
@GolanTrevize10 it will function if you use `3.6`... unfortunately the `Pipfile` only allows for a single version of Python to be required, so we can't set a minimum version and have it pick something newer. If you change the `Pipfile` to be `3.6` it _should_ still function, as I don't believe we're using any of the 3.7+ features.

**Comment by GolanTrevize10** [comment]
It looks like it does not work with latest pipenv version because it does not support 3.6. So I will try with 3.9

**Comment by VanyaBerzoi** [comment]
> In the Readme file it says it needs Python 3.4+, but in the pipfile it says it requires 3.9

**Comment by GolanTrevize10** [comment]
It is not possible to make it work in Python 3.4 unless you use an older version of pipenv

**Comment by primetheus** [comment]
Unfortunately `pipenv` is limited to declaring only a single version in the file. The code itself works when not using pipenv, or if you use an older version of pipenv. I don't know the best way to handle that, since it's technically not a limitation of this app, but of pipenv (by design). I'm open to suggestions, whether we update the README, or however else we want to handle it

**Comment by primetheus** [comment]
@GolanTrevize10 I opened #144 to clarify... would like your input on that, if you have time 🙏🏽
