### ISSUE TITLE
Merging of 2 accounts on Github -feature request

### ISSUE THREAD

**Issue by brundabharadwaj** [github/github-team-sync#149]
- Able to merge 2 or more accounts into a single on user request
- Able to transfer the badges earned on git hub to the account merged

**Comment by primetheus** [comment]
@brundabharadwaj thank you for opening this issue! So that I understand the full scope of this request, can you clarify a few things?

>Able to merge 2 or more accounts into a single on user request

What sort of merging are you looking to accomplish with this? Right now it's synchronizing teams in GitHub organizations with groups in various directory services. It doesn't currently make any changes to user attributes or accounts

>Able to transfer the badges earned on git hub to the account merged

Are you thinking of merging two individual user accounts in GitHub into a single account? If so, this is more of a product feature that GitHub would have to implement. This utility isn't aimed at user management, but synchronizing team memberships

**Comment by brundabharadwaj** [comment]
Yes you are right, I am asking about merging of  2 individual user accounts  !

**Comment by primetheus** [comment]
Ok, that makes sense. I'm going to close out this issue, as it's outside of what this application does. There is a [doc here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/merging-multiple-personal-accounts) that guides you through the process, but it's not an automated process
